// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for sample.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const sampleBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/sample.bridge.ts
  (function() {
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || e.data.type !== "agent-native:sample-ping") return;
      var correlationId = e.data.correlationId ?? "";
      try {
        window.parent.postMessage(
          { type: "agent-native:sample-pong", correlationId },
          "*"
        );
      } catch (_err) {
      }
    });
  })();
})();
`;
