[build]
  ignore = "node ./scripts/netlify-ignore-build.mjs starter"
  command = "export DATABASE_URL=${NETLIFY_DATABASE_URL:-$DATABASE_URL} && pnpm install && NITRO_PRESET=netlify pnpm --filter starter build"
  publish = "templates/starter/dist"
  functions = "templates/starter/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
  NPM_CONFIG_PRODUCTION = "false"
