// Framework for agent-native apps.
// Import everything from "@agent-native/core".

// Agent (production mode)
export {
  createProductionAgentHandler,
  type ActionEntry,
  type ScriptEntry,
  type ProductionAgentOptions,
  type ActionTool,
  type ScriptTool,
  type AgentMessage,
  type AgentChatRequest,
  type AgentChatEvent,
  type AgentChatAttachment,
  DEFAULT_MODEL,
} from "./agent/index.js";
export {
  defineAction,
  AgentActionStopError,
  isAgentActionStopError,
  type ActionHttpConfig,
  type AgentActionStopOptions,
  type PublicAgentActionConfig,
  type ActionDeepLink,
  type ActionLinkBuilder,
  MCP_APP_EXTENSION_ID,
  MCP_APP_MIME_TYPE,
  MCP_APP_RESOURCE_URI_META_KEY,
  type ActionMcpAppConfig,
  type ActionMcpAppCsp,
  type ActionMcpAppCspBuilder,
  type ActionMcpAppHtmlBuilder,
  type ActionMcpAppPermissions,
  type ActionMcpAppResourceConfig,
  type ActionMcpAppResourceMeta,
} from "./action.js";
export {
  embedApp,
  MCP_APP_REQUEST_ORIGIN_CSP_SOURCE,
  type EmbedAppOptions,
} from "./mcp/embed-app.js";
export {
  embedRoute,
  type EmbedRouteContext,
  type EmbedRouteOptions,
  type EmbedRoutePathBuilder,
  type EmbedRouteResult,
} from "./mcp/embed-route.js";
export { createDevScriptRegistry } from "./scripts/dev/index.js";
export {
  createAgentChatPlugin,
  defaultAgentChatPlugin,
  type AgentChatPluginOptions,
} from "./server/agent-chat-plugin.js";
export {
  createAgentNativeEmbeddedPlugin,
  mountAgentNativeEmbedded,
  type AgentNativeEmbeddedPluginOptions,
} from "./server/embedded.js";

// Server
export {
  createServer,
  createSSEHandler,
  defineNitroPlugin,
  autoMountAuth,
  getSession,
  type CreateServerOptions,
  type SSEHandlerOptions,
  type AuthSession,
  type AuthOptions,
} from "./server/index.js";

// Client
export {
  sendToAgentChat,
  useAgentChatGenerating,
  useDevMode,
  useSendToAgentChat,
  AGENT_NATIVE_MCP_APP_HOST_MESSAGE_TYPES,
  getMcpAppHostContext,
  openMcpAppHostLink,
  requestMcpAppDisplayMode,
  updateMcpAppModelContext,
  useMcpAppHostContext,
  CodeRequiredDialog,
  useAgentNativeEmbeddedBrowserSession,
  useDbSync,
  useFileWatcher,
  cn,
  ApiKeySettings,
  useSession,
  AgentNativeEmbedded,
  useProductionAgent,
  ProductionAgentPanel,
  type AgentChatMessage,
  type AgentNativeMcpAppHostMessageType,
  type McpAppDisplayMode,
  type McpAppHostCapabilities,
  type McpAppHostContext,
  type McpAppHostContextSnapshot,
  type McpAppModelContextContentPart,
  type McpAppModelContextUpdate,
  type AgentNativeEmbeddedProps,
  type UseAgentNativeEmbeddedBrowserSessionOptions,
  type CodeRequiredDialogProps,
  type ProductionAgentMessage,
  type UseProductionAgentResult,
  type ProductionAgentPanelProps,
  useActionQuery,
  useActionMutation,
} from "./client/index.js";

// Shared (isomorphic)
export {
  agentChat,
  type AgentChatCallOptions,
  type AgentChatResponse,
} from "./shared/index.js";
export {
  EMBED_MODE_QUERY_PARAM,
  EMBED_SESSION_COOKIE,
  EMBED_START_PATH,
  EMBED_TOKEN_QUERY_PARAM,
} from "./shared/embed-auth.js";

// Agent Web surfaces
export {
  AGENT_WEB_CRAWLER_CATEGORIES,
  AGENT_WEB_CRAWLER_USER_AGENTS,
  DEFAULT_AGENT_WEB_CRAWLER_POLICY,
  absoluteUrl,
  agentWebConfigFromPackageJson,
  buildAgentWebStaticFiles,
  buildBaseJsonLd,
  buildLlmsFullTxt,
  buildLlmsTxt,
  buildMarkdownResponseHeaders,
  buildPageJsonLd,
  buildRobotsTxt,
  buildSitemapXml,
  deriveAgentWebPublicRoutes,
  estimateMarkdownTokens,
  markdownFilePathForPage,
  markdownUrlForPage,
  normalizeAgentWebConfig,
  pathPatternMatches,
  resolveAgentWebCrawlerPolicy,
  type AgentWebConfig,
  type AgentWebCrawlerCategory,
  type AgentWebCrawlerDecision,
  type AgentWebCrawlerOverrides,
  type AgentWebCrawlerPolicy,
  type AgentWebInputConfig,
  type AgentWebPage,
  type AgentWebStaticFile,
  type BuildAgentWebStaticFilesOptions,
  type DeriveAgentWebPublicRoutesOptions,
  type MarkdownResponseHeadersOptions,
} from "./agent-web/index.js";

// Token usage tracking
export {
  recordUsage,
  getUsageSummary,
  getUserUsageCents,
  calculateCost,
  usageBillingForEngine,
  builderCreditsFromCostCents,
  BUILDER_AGENT_CREDIT_MARGIN_MULTIPLIER,
  BUILDER_AGENT_CREDITS_PER_USD,
  BUILDER_CREDIT_USAGE_BILLING,
  USD_USAGE_BILLING,
  type UsageRecord,
  type UsageSummary,
  type UsageBillingMode,
  type UsageBillingUnit,
  type UsageBucket,
  type DailyBucket,
  type UsageRecentEntry,
} from "./usage/store.js";

// Workspace-scoped third-party connection metadata
export {
  deleteWorkspaceConnection,
  getWorkspaceConnectionAppAccess,
  getWorkspaceConnection,
  getWorkspaceConnectionGrant,
  listWorkspaceConnectionProviderCatalogForApp,
  listWorkspaceConnectionGrants,
  listWorkspaceConnections,
  resolveWorkspaceConnectionCredentialForApp,
  resolveWorkspaceConnectionCredentialsForApp,
  revokeWorkspaceConnectionGrant,
  serializeWorkspaceConnectionGrant,
  serializeWorkspaceConnection,
  summarizeWorkspaceConnectionProviderForApp,
  summarizeWorkspaceConnectionProviderReadiness,
  upsertWorkspaceConnectionGrant,
  upsertWorkspaceConnection,
  type ListWorkspaceConnectionProviderCatalogForAppOptions,
  type ListWorkspaceConnectionGrantsOptions,
  type ListWorkspaceConnectionsOptions,
  type ResolveWorkspaceConnectionCredentialForAppOptions,
  type ResolveWorkspaceConnectionCredentialsForAppOptions,
  type SerializedWorkspaceConnectionGrant,
  type SerializedWorkspaceConnection,
  type SummarizeWorkspaceConnectionProviderForAppOptions,
  type SummarizeWorkspaceConnectionProviderReadinessOptions,
  type UpsertWorkspaceConnectionGrantInput,
  type UpsertWorkspaceConnectionInput,
  type WorkspaceConnectionAppAccess,
  type WorkspaceConnectionAppAccessMode,
  type WorkspaceConnection,
  type WorkspaceConnectionCredentialBackend,
  type WorkspaceConnectionCredentialProvenance,
  type WorkspaceConnectionCredentialRef,
  type WorkspaceConnectionCredentialResolution,
  type WorkspaceConnectionCredentialResolutionCheck,
  type WorkspaceConnectionCredentialResolutionStatus,
  type WorkspaceConnectionCredentialsResolution,
  type WorkspaceConnectionExplicitGrantSummary,
  type WorkspaceConnectionForAppSummary,
  type WorkspaceConnectionGrant,
  type WorkspaceConnectionGrantAvailability,
  type WorkspaceConnectionGrantState,
  type WorkspaceConnectionProviderAppSummary,
  type WorkspaceConnectionProviderLike,
  type WorkspaceConnectionProviderCatalogForApp,
  type WorkspaceConnectionProviderCatalogForAppItem,
  type WorkspaceConnectionProviderReadiness,
  type WorkspaceConnectionProviderReadinessStatus,
  type WorkspaceConnectionPublicCredentialRef,
  type WorkspaceConnectionStatus,
  workspaceConnectionIsAvailableToApp,
} from "./workspace-connections/index.js";

// Reusable workspace connection provider catalog
export {
  PROVIDER_READERS,
  ProviderReaderRuntimeError,
  WORKSPACE_CONNECTION_PROVIDERS,
  createProviderReaderRuntime,
  defineProviderReader,
  defineProviderReaderImplementation,
  defineWorkspaceConnectionProvider,
  getProviderReader,
  getWorkspaceConnectionProvider,
  isWorkspaceConnectionProviderId,
  listProviderReaders,
  listWorkspaceConnectionProviders,
  listWorkspaceConnectionProvidersForCapability,
  listWorkspaceConnectionProvidersForTemplate,
  providerReaderSupports,
  workspaceConnectionProviderSupports,
  type ListWorkspaceConnectionProvidersOptions,
  type ListProviderReadersOptions,
  type ProviderReaderCapability,
  type ProviderReaderCredentialRequirement,
  type ProviderReaderDefinition,
  type ProviderReaderImplementationStatus,
  type ProviderReaderOperation,
  type ProviderReaderOperationDescriptor,
  type ProviderReaderOperationParameter,
  type ProviderReaderRequest,
  type ProviderReaderRuntime,
  type ProviderReaderRuntimeConnection,
  type ProviderReaderRuntimeConnectionResolverOptions,
  type ProviderReaderRuntimeContext,
  type ProviderReaderRuntimeCredentialsResolverOptions,
  type ProviderReaderRuntimeErrorCode,
  type ProviderReaderRuntimeHandler,
  type ProviderReaderRuntimeImplementation,
  type ProviderReaderRuntimeItem,
  type ProviderReaderRuntimeOptions,
  type ProviderReaderRuntimeResponse,
  type WorkspaceConnectionCapability,
  type WorkspaceConnectionCredentialKey,
  type WorkspaceConnectionProvider,
  type WorkspaceConnectionProviderId,
  type WorkspaceConnectionTemplateUse,
} from "./connections/index.js";

// Scripts
export {
  runScript,
  loadEnv,
  parseArgs,
  camelCaseArgs,
  isValidPath,
  isValidProjectPath,
  ensureDir,
  fail,
} from "./scripts/index.js";

// Secrets registry — import from "@agent-native/core/secrets" when possible
// (the subpath keeps the top-level entry point lean), but re-export the
// public API here for convenience.
export {
  registerRequiredSecret,
  listRequiredSecrets,
  getRequiredSecret,
  readAppSecret,
  writeAppSecret,
  deleteAppSecret,
  type RegisteredSecret,
  type SecretScope,
  type SecretKind,
  type SecretValidator,
  type SecretRef,
} from "./secrets/index.js";
