[build]
ignore = "node ./scripts/netlify-ignore-build.mjs macros"
command = "export DATABASE_URL=${NETLIFY_DATABASE_URL:-$DATABASE_URL} && pnpm install && DATABASE_URL=${NETLIFY_DATABASE_URL_UNPOOLED:-$DATABASE_URL} NITRO_PRESET=netlify pnpm --filter macros build"
publish = "templates/macros/dist"
functions = "templates/macros/.netlify/functions-internal"

[build.environment]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"
GTM_CONTAINER_ID = "GTM-N3WSTXZ"
NITRO_PRESET = "netlify"
NPM_CONFIG_PRODUCTION = "false"
